# =========================================================
# PRODUCTION DATABASE TARGET (RENDER CLOUD)
# =========================================================
spring.datasource.url=jdbc:postgresql://householdchores_postgres_user:Vs0UMeciX3EUgG4Nn7RpaOUjcTd7JjJs@dpg-d8fg204m0tmc73evip6g-a:5432/householdchores_postgres
spring.datasource.username=householdchores_postgres_user
spring.datasource.password=Vs0UMeciX3EUgG4Nn7RpaOUjcTd7JjJs
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update