spring.config.import=optional:file:env.properties
spring.application.name=householdchores_postgres

# SERVER CONFIG
server.port=${PORT}

# DB CONFIG reconstructs dynamically based on your variables
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=50

# JWT
jwt.secret=${JWT_SECRET}

# CLOUDINARY
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apiKey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_API_SECRET}

# MAILGUN
mailgun.domainName=${MAILGUN_DOMAIN_NAME}
mailgun.apiKey=${MAILGUN_API_KEY}
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:10MB}

# Local Development Environment
app.frontend.url=${FRONTEND_URL:http://localhost:5173}
