package raposinha.houseHoldChores.repositories;

import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import raposinha.houseHoldChores.entities.Task;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Repository
public interface TaskRepo extends JpaRepository<Task, Long> {

    // weekly calendar: fetches all tasks for a group between two dates
    List<Task> findByGroup_IdAndDueDateBetween(Long groupId, LocalDateTime start, LocalDateTime end);

    // only the tasks assigned to a specific person
    List<Task> findByAssignedToId(UUID userId);

    // tasks that are overdue and not completed
    List<Task> findByIsCompletedFalseAndDueDateBefore(LocalDateTime now);

    @Modifying // Required for queries modifying the database state
    @Query("UPDATE Task t SET t.assignedTo = null WHERE t.assignedTo.id = :userId")
    void unassignTasksByUserId(@Param("userId") UUID userId);
    List<Task> findByGroupId(UUID groupId);

    // Find template tasks (created by users, not generated by scheduler)
    @Query("SELECT t FROM Task t WHERE t.parentTask IS NULL AND t.group IS NOT NULL")
    List<Task> findAllUserCreatedTasks();

    // Find the latest generated occurrence for a given template
    @Query("SELECT t FROM Task t WHERE t.parentTask.id = :parentId ORDER BY t.dueDate DESC")
    List<Task> findOccurrencesSortedByDueDate(@Param("parentId") Long parentId, Pageable pageable);

    @Modifying
    @Query("DELETE FROM Task t WHERE t.parentTask.id = :templateId AND t.dueDate > :now AND t.isCompleted = false")
    void deleteFutureOccurrences(@Param("templateId") Long templateId, @Param("now") LocalDateTime now);

    @Query("SELECT t.id FROM Task t WHERE t.parentTask.id = :templateId AND t.dueDate > :now AND t.isCompleted = false")
    List<Long> findFutureOccurrenceIds(@Param("templateId") Long templateId, @Param("now") LocalDateTime now);



}